Add lda_infer program and unit testing tools.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -746,6 +746,15 @@ OTOOL64
 CXXCPP
 GCC_TRUE
 GCC_FALSE
+GTEST_CONFIG
+GTEST_CPPFLAGS
+GTEST_CXXFLAGS
+GTEST_LDFLAGS
+GTEST_LIBS
+GTEST_VERSION
+HAVE_GTEST
+HAVE_GTEST_TRUE
+HAVE_GTEST_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -761,7 +770,13 @@ CCC
 CC
 CFLAGS
 CPP
-CXXCPP'
+CXXCPP
+GTEST_CONFIG
+GTEST_CPPFLAGS
+GTEST_CXXFLAGS
+GTEST_LDFLAGS
+GTEST_LIBS
+GTEST_VERSION'
 
 
 # Initialize some variables set by options.
@@ -1348,6 +1363,8 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-gtest          Enable tests using the Google C++ Testing Framework.
+                          (Default is enabled.)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1368,6 +1385,17 @@ Some influential environment variables:
   CFLAGS      C compiler flags
   CPP         C preprocessor
   CXXCPP      C++ preprocessor
+  GTEST_CONFIG
+              The exact path of Google Test's 'gtest-config' script.
+  GTEST_CPPFLAGS
+              C-like preprocessor flags for Google Test.
+  GTEST_CXXFLAGS
+              C++ compile flags for Google Test.
+  GTEST_LDFLAGS
+              Linker path and option flags for Google Test.
+  GTEST_LIBS  Library linking flags for Google Test.
+  GTEST_VERSION
+              The version of Google Test available.
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -18579,6 +18607,144 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
+
+# Check whether --enable-gtest was given.
+if test "${enable_gtest+set}" = set; then
+  enableval=$enable_gtest;
+else
+  enable_gtest=no
+fi
+
+
+
+
+
+
+
+
+HAVE_GTEST="no"
+if test "x${enable_gtest}" != "xno"; then
+  { echo "$as_me:$LINENO: checking for 'gtest-config'" >&5
+echo $ECHO_N "checking for 'gtest-config'... $ECHO_C" >&6; }
+   if test "x${enable_gtest}" != "xyes"; then
+  if test -x "${enable_gtest}/scripts/gtest-config"; then
+  GTEST_CONFIG="${enable_gtest}/scripts/gtest-config"
+else
+  GTEST_CONFIG="${enable_gtest}/bin/gtest-config"
+fi
+
+      if test -x "${GTEST_CONFIG}"; then
+  :
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+         { { echo "$as_me:$LINENO: error: Unable to locate either a built or installed Google Test.
+The specific location '${enable_gtest}' was provided for a built or installed
+Google Test, but no 'gtest-config' script could be found at this location." >&5
+echo "$as_me: error: Unable to locate either a built or installed Google Test.
+The specific location '${enable_gtest}' was provided for a built or installed
+Google Test, but no 'gtest-config' script could be found at this location." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+else
+  # Extract the first word of "gtest-config", so it can be a program name with args.
+set dummy gtest-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GTEST_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GTEST_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GTEST_CONFIG="$GTEST_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GTEST_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GTEST_CONFIG=$ac_cv_path_GTEST_CONFIG
+if test -n "$GTEST_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $GTEST_CONFIG" >&5
+echo "${ECHO_T}$GTEST_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+
+   if test -x "${GTEST_CONFIG}"; then
+  { echo "$as_me:$LINENO: result: ${GTEST_CONFIG}" >&5
+echo "${ECHO_T}${GTEST_CONFIG}" >&6; }
+      _gtest_min_version="--min-version=1.0"
+         { echo "$as_me:$LINENO: checking for Google Test at least version >= 1.0" >&5
+echo $ECHO_N "checking for Google Test at least version >= 1.0... $ECHO_C" >&6; }
+      if ${GTEST_CONFIG} ${_gtest_min_version}; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+         HAVE_GTEST='yes'
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+   if test "x${HAVE_GTEST}" = "xyes"; then
+  GTEST_CPPFLAGS=`${GTEST_CONFIG} --cppflags`
+      GTEST_CXXFLAGS=`${GTEST_CONFIG} --cxxflags`
+      GTEST_LDFLAGS=`${GTEST_CONFIG} --ldflags`
+      GTEST_LIBS=`${GTEST_CONFIG} --libs`
+      GTEST_VERSION=`${GTEST_CONFIG} --version`
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTEST 1
+_ACEOF
+
+else
+  if test "x${enable_gtest}" = "xyes"; then
+  { { echo "$as_me:$LINENO: error: Google Test was enabled, but no viable version could be found." >&5
+echo "$as_me: error: Google Test was enabled, but no viable version could be found." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+
+fi
+
+
+ if test "x$HAVE_GTEST" = "xyes"; then
+  HAVE_GTEST_TRUE=
+  HAVE_GTEST_FALSE='#'
+else
+  HAVE_GTEST_TRUE='#'
+  HAVE_GTEST_FALSE=
+fi
+
+
+
 ac_config_files="$ac_config_files Makefile src/Makefile"
 
 cat >confcache <<\_ACEOF
@@ -18716,6 +18882,13 @@ if test -z "${GCC_TRUE}" && test -z "${GCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"GCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"GCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_GTEST_TRUE}" && test -z "${HAVE_GTEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_GTEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_GTEST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -19765,11 +19938,20 @@ OTOOL64!$OTOOL64$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 GCC_TRUE!$GCC_TRUE$ac_delim
 GCC_FALSE!$GCC_FALSE$ac_delim
+GTEST_CONFIG!$GTEST_CONFIG$ac_delim
+GTEST_CPPFLAGS!$GTEST_CPPFLAGS$ac_delim
+GTEST_CXXFLAGS!$GTEST_CXXFLAGS$ac_delim
+GTEST_LDFLAGS!$GTEST_LDFLAGS$ac_delim
+GTEST_LIBS!$GTEST_LIBS$ac_delim
+GTEST_VERSION!$GTEST_VERSION$ac_delim
+HAVE_GTEST!$HAVE_GTEST$ac_delim
+HAVE_GTEST_TRUE!$HAVE_GTEST_TRUE$ac_delim
+HAVE_GTEST_FALSE!$HAVE_GTEST_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 25; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/src/Makefile.in b/src/Makefile.in
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -34,15 +34,17 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-bin_PROGRAMS = lda_learn$(EXEEXT)
+bin_PROGRAMS = lda_learn$(EXEEXT) lda_infer$(EXEEXT)
+check_PROGRAMS =
+TESTS =
 subdir = src
 DIST_COMMON = $(include_HEADERS) $(srcdir)/Makefile.am \
 	$(srcdir)/Makefile.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
-am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
-	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
-	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
-	$(top_srcdir)/configure.in
+am__aclocal_m4_deps = $(top_srcdir)/m4/gtest.m4 \
+	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
+	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
+	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.in
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
 mkinstalldirs = $(install_sh) -d
@@ -63,6 +65,9 @@ am_libminilda_la_OBJECTS = libminilda.lo gibbs_sampler.lo
 libminilda_la_OBJECTS = $(am_libminilda_la_OBJECTS)
 binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
 PROGRAMS = $(bin_PROGRAMS)
+am_lda_infer_OBJECTS = lda_infer.$(OBJEXT)
+lda_infer_OBJECTS = $(am_lda_infer_OBJECTS)
+lda_infer_DEPENDENCIES = libminilda.la
 am_lda_learn_OBJECTS = lda_learn.$(OBJEXT)
 lda_learn_OBJECTS = $(am_lda_learn_OBJECTS)
 lda_learn_DEPENDENCIES = libminilda.la
@@ -78,8 +83,10 @@ CXXLD = $(CXX)
 CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
 	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
 	$(LDFLAGS) -o $@
-SOURCES = $(libminilda_la_SOURCES) $(lda_learn_SOURCES)
-DIST_SOURCES = $(libminilda_la_SOURCES) $(lda_learn_SOURCES)
+SOURCES = $(libminilda_la_SOURCES) $(lda_infer_SOURCES) \
+	$(lda_learn_SOURCES)
+DIST_SOURCES = $(libminilda_la_SOURCES) $(lda_infer_SOURCES) \
+	$(lda_learn_SOURCES)
 includeHEADERS_INSTALL = $(INSTALL_HEADER)
 HEADERS = $(include_HEADERS)
 ETAGS = etags
@@ -113,6 +120,13 @@ EGREP = @EGREP@
 EXEEXT = @EXEEXT@
 FGREP = @FGREP@
 GREP = @GREP@
+GTEST_CONFIG = @GTEST_CONFIG@
+GTEST_CPPFLAGS = @GTEST_CPPFLAGS@
+GTEST_CXXFLAGS = @GTEST_CXXFLAGS@
+GTEST_LDFLAGS = @GTEST_LDFLAGS@
+GTEST_LIBS = @GTEST_LIBS@
+GTEST_VERSION = @GTEST_VERSION@
+HAVE_GTEST = @HAVE_GTEST@
 INSTALL = @INSTALL@
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
@@ -221,6 +235,11 @@ libminilda_la_SOURCES = \
 include_HEADERS = minilda.h
 lda_learn_SOURCES = lda_learn.cc
 lda_learn_LDADD = libminilda.la
+lda_infer_SOURCES = lda_infer.cc
+lda_infer_LDADD = libminilda.la
+
+# unit tests you want to run when people type 'make check'.
+@HAVE_GTEST_TRUE@TESTHARNESS = testharness.cc
 all: all-am
 
 .SUFFIXES:
@@ -311,6 +330,16 @@ clean-binPROGRAMS:
 	  echo " rm -f $$p $$f"; \
 	  rm -f $$p $$f ; \
 	done
+
+clean-checkPROGRAMS:
+	@list='$(check_PROGRAMS)'; for p in $$list; do \
+	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
+	  echo " rm -f $$p $$f"; \
+	  rm -f $$p $$f ; \
+	done
+lda_infer$(EXEEXT): $(lda_infer_OBJECTS) $(lda_infer_DEPENDENCIES) 
+	@rm -f lda_infer$(EXEEXT)
+	$(CXXLINK) $(lda_infer_OBJECTS) $(lda_infer_LDADD) $(LIBS)
 lda_learn$(EXEEXT): $(lda_learn_OBJECTS) $(lda_learn_DEPENDENCIES) 
 	@rm -f lda_learn$(EXEEXT)
 	$(CXXLINK) $(lda_learn_OBJECTS) $(lda_learn_LDADD) $(LIBS)
@@ -401,6 +430,79 @@ GTAGS:
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; ws='[	 ]'; \
+	srcdir=$(srcdir); export srcdir; \
+	list=' $(TESTS) '; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *$$ws$$tst$$ws*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *$$ws$$tst$$ws*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    skipped="($$skip tests were not run)"; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
+
 distdir: $(DISTFILES)
 	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
@@ -428,6 +530,8 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS)
 install-binPROGRAMS: install-libLTLIBRARIES
@@ -462,8 +566,8 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
-	clean-libtool mostlyclean-am
+clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
+	clean-libLTLIBRARIES clean-libtool mostlyclean-am
 
 distclean: distclean-am
 	-rm -f Makefile
@@ -520,13 +624,14 @@ uninstall-am: uninstall-binPROGRAMS uninstall-includeHEADERS \
 
 .MAKE: install-am install-strip
 
-.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
-	clean-generic clean-libLTLIBRARIES clean-libtool ctags \
-	distclean distclean-compile distclean-generic \
-	distclean-libtool distclean-tags distdir dvi dvi-am html \
-	html-am info info-am install install-am install-binPROGRAMS \
-	install-data install-data-am install-dvi install-dvi-am \
-	install-exec install-exec-am install-html install-html-am \
+.PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
+	clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
+	clean-libLTLIBRARIES clean-libtool ctags distclean \
+	distclean-compile distclean-generic distclean-libtool \
+	distclean-tags distdir dvi dvi-am html html-am info info-am \
+	install install-am install-binPROGRAMS install-data \
+	install-data-am install-dvi install-dvi-am install-exec \
+	install-exec-am install-html install-html-am \
 	install-includeHEADERS install-info install-info-am \
 	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
 	install-ps install-ps-am install-strip installcheck \
